{% set version = "19.1" %}

package:
  name: packaging
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/packaging/packaging-{{ version }}.tar.gz
  sha256: c491ca87294da7cc01902edbe30a5bc6c4c28172b5138ab4e4aa1b9d7bfaeafe

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - pyparsing
    - six

  run:
    - python
    - pyparsing
    - six

test:
  imports:
    - packaging

about:
  home: https://github.com/pypa/packaging
  license: Apache 2.0 or BSD 2-Clause
  license_file: LICENSE
  summary: Core utilities for Python packages

extra:
  recipe-maintainers:
    - jakirkham
    - nicoddemus
