{% set version = "21.2" %}

package:
  name: packaging
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/packaging/packaging-{{ version }}.tar.gz
  sha256: 096d689d78ca690e4cd8a89568ba06d07ca097e3306a4381635073ca91479966

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - setuptools >=40.8
    - pip

  run:
    - python >=3.6
    - pyparsing >=2.0.2

test:
  imports:
    - packaging

about:
  home: https://github.com/pypa/packaging
  license: Apache-2.0
  license_file: LICENSE
  summary: Core utilities for Python packages

extra:
  recipe-maintainers:
    - jakirkham
    - nicoddemus
