travis:
  secure:
    BINSTAR_TOKEN: tG6j4Vwdy4yIEtRZ5Pe8w0d/8Ttn/PWbEs6f5gYaVoM1BLKdTel1AfLwhPJVZfjHZZdBUFR2+ZjTbgtpWc5G0HRlJzqk9EEl6xrPFb0/Rp9MNrdjyJuO/Wh3GnwYh7lUa9jor2vZ6M8PGHUlMfbTAHZRNLnEuj5uVBfO3rEMmSR1vEuYUCeXOBXV9UGebkXrbjGCUP8LLXhSZYcaWwd3Jvw9fc/wo1U8aMxUbdAPJARdF0sdVOhQ9SM0UbudKx8PWO5A9EFRdsKi10OQZqk7a4zu369nTPXA0eN+AVFE3zDjmb76zOA0AU2wlSsQwW17+2TKAIYyIVlX6mPBdIfR6hWuXIAbZIItLeBBfu6x0D1vNizveXrlnXgggUIPzXJkzUjPD5K1HjcpSfYfJjSlOcIRsNQdqSBsnUIhMwcU7Xc0M+QsW4OP0+0TqJnX9nv0/ByQYj1DBGROdqsE9UmY4GEUupRFumOlk7cRTDWKeRZPFwdUpv7NGuFYjhOKiPUpKP+291VQPk3pq4dZcvj3pFUqLX7M8xJMTApemKlp6IoYObudAv/WhTsf0jHCYQSqTmdmi9ZcQqNz3qFOG3OAogzI+SqRS6MzMIZFRVSNCvbdGPNEUpYqWW34fkmypiL0r/xsiL77bp1upiy7MKnaGTyNbJrMG6VufwvVRbW+VNI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
